var taxCopy = "Being married or having a family will both offer tax breaks, but these might not matter at all! Some investment accounts are not taxed upon withdrawal. We've made sure to note these accounts below.";


var intro401Copy = "Many employers will offer to match some percentage of your contributions to your 401k, netting you more money saved for retirement.\n";
var general401Copy = "401ks are accounts which offer an average of 5-8% return on your contributions each year and are usually tied to an employer. Many employers will match some of your contributions to your 401k. For this reason alone, 401ks are a good place to start. There is a contribution limit for both 401k accounts of $22,500 for 2023, and this amount gets adjusted each year. 401ks cannot be treated like a regular savings account. You will be penalized for all withdrawals made before you are 59 and one-half years of age. For this reason, 401ks are to be treated primarily as retirement accounts. This is one feature that some other accounts do not share.";
var traditional401Copy = "Traditional 401k accounts allow you to subtract your contributions from your taxable income. This may knock you down an entire tax bracket and, even if not, will certainly save you some in taxes each year. The downside is that your withdrawals from this account during retirement will be taxed. This means that the taxes you pay in the long run will likely be higher for a number of reasons. This may be because your total 401k account value will be higher when you retire than the sum of your contributions, so you will have more total money on which to be taxed. This may also be because your tax rate may be higher when you retire if you were making more money towards the end of your career. Another reason this could be higher is that tax rates in general may have increased. If you need the tax break now, or if you're confident about what your tax bracket will be when you retire, a traditional 401k is a good choice.";
var roth401Copy = "Roth 401k accounts can be contributed to with your after-tax income. This means that your total income will be taxed against even if you contribute to a Roth 401k. The benefit to taking this hit now is that your withdrawals from this account during retirement will not be taxed. This could be a benefit in certain situations. If you know you will be making more money and be in a higher tax bracket later in your career, this will save you some money in taxes. If you are feeling confident that tax rates will go up over the course of your life (or are simply worried about the possibility of this), this is a good way to hedge against that, too.";
var ending401Copy = "Each 401k account has its benefits and drawbacks. While the total sum you can contribute to either is still $22,500 each year, you are welcome to contribute to both if you are interested in some of the benefits each offers.";

var introIraCopy = "IRAs are retirement accounts that you manage. They often offer higher rates of returns than 401ks.\n";
var generalIraCopy = "An Individual Retirement Account (IRA) is a retirement account which offers an average of 7-10% return on your contributions each year. Unlike a 401k, this account is managed by you and not your employer. Also unlike a 401k, withdrawals can be made from this account before the age of 59-and-a-half for certain reasons, inlcuding certain education-related loans, first-time home purchases, major medical expenses or long-term unemployment expenses. In this way, IRAs are a little more flexible than 401ks.";
var traditionalIraCopy = "Traditional IRAs are usually contributed to with after-tax income, though contributions can be tax deductible (lower your taxable income) if certain conditions are met. Contributions are entirely deductible if you make less than $68,000 single or $109,000 as a married couple. Contributions are partially tax-deductible if you make less than $78,000 single or $129,000 as a married couple. Because you may benefit from these tax breaks, your earnings and contributions will be taxed upon withdrawal. This makes this an attractive option if you are eligible for the tax deduction and/or believe that your tax bracket may be lower when you withdraw then it is when you are contributing.";
var rothIraCopy = "Roth IRAs are contributed to with after-tax money and contributions are not tax deductible. Because of this, you are able to withdraw the contributions and its earnings tax free. This is a good perk as the total amount of money in your IRA will be more than you contributed, lowering total taxes paid. In addition, if your taxable income later in your career is higher than it is when you contribute, you will also save in taxes this way, as you will dodge this higher tax rate when you are withdrawing. These tax benefits are substantial, so much so that there are income limits on those that may contribute and benefit from this account. For singles, the income limit is $129,000. For those filing jointly, the income limit is $204,000.";
var iraEndingCopy = "While an employer may not match your contributions to an IRA, this is still a very strong account type. With high expected rates of return and considerable tax benefits, including an IRA in your retirement account portfolio is likely a good decision.";

var introHighYieldSavingsAccountCopy = "HYSAs are flexible, risk free ways of growing your money. They offer lower rates of return than some other accounts.\n";
var highYieldSavingsAccountCopy = "A high-yield savings account is a flexible and risk-free option for a retirement account. With average rates of return between 2-4% and no employer match, this puts it on the lower end of the spectrum, but unlike 401ks or IRAs, the performance of a high-yield savings account is not tied to the performance of the economy/whichever portfolios you or your company has decided to invest in. This is guaranteed year after year growth and, if you open a HYSA with an FDIC-insured bank, you are guaranteed to never lose a cent of your money up to $250,000. This, with the added flexibility of being able to deposit and withdraw whenever you like with no penalties, make this an attractive account type, particularly for extra cash or during times of economic uncertainty.";

var introCdCopy = "CDs are risk-free ways of growing your money. They offer medium-low rates of return on your money relative to some other accounts.\n";
var cdCopy = "A certificate of deposit (CD) is a savings item which returns an average rate of return of 4-5%. When you purchase a certificate of deposit, you agree to store an amount of money for a period of time with a guaranteed interest rate. After the CD has 'matured' (after this period of time is up), you may withdraw your original amount of money plus the interest it has earned. CDs trade off some flexibility for higher returns relative to High Yield Savings Accounts, as you can not touch the money for the duration agreed upon but the rate of return will often be higher. In an emergency, it is possible to withdraw your money, but expect some penalties. If you are otherwise unprepared for emergencies, it may be smarter to consider a High Yield Savings Account.";

var introSnP = "Comparing your contributions in a retirement account to the performance of the S&P 500 allows you to see how your contributions could grow if you invest in a similar index fund.\n";
var sAndPCopy = "The Standard and Poor's 500 (S&P 500) is a stock market index tracking the stock performance of 500 of the largest companies in the United States. The S&P 500 is a good indicator of the health of the stock market and can be used as a kind of baseline against these other accounts. While it does not offer any tax benefits, you could also consider investing directly into similar index funds. With the S&P 500's average rate of return at 10% over the last 30 years, it beats many of these account types. However, it is very market dependent and you could see your investments fluctuating year after year. It has shown to be a long-term benefit across a number of decades, so if you can handle some year-to-year fluctuations and the accompanying risk, the S&P 500 may be a solid method for building your retirement portfolio.";